name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  flake8:
    name: Run flake8 checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install tox
      - run: tox -e flake8

  black:
    name: Run black
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install tox
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install tox
      - run: tox -e black
